#! /bin/sh
if [ $# -ne 2 ]; then
  echo "Usage:"
  echo "git wip [branch-name] [commit-message]"
  exit 2
fi
git pull origin master
git checkout -b $1
git commit --allow-empty -m "Start Branch for '$2'"
git push origin $1
